# Generated by Django 6.0 on 2026-01-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_complaint', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comp',
            name='c_date',
            field=models.DateField(verbose_name='Date(YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='complainant_name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='complaint_desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='comp',
            name='complaint_type',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
    ]
